services:
  # --- BANCO DE DADOS ---
  db:
    build:
      context: .     
      dockerfile: Dockerfile  # Nome do arquivo dentro da pasta backend
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20

  # --- API .NET ---
  api:
    build:
      context: .       
      dockerfile: Dockerfile.api 
    container_name: dotnet_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ecommerce;Uid=root;Pwd=pass;

 